name: remote ssh command
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ${{ github.event.repository.name }}
          whoami

        host: ${{ vars.HOST }}
        user: ${{ vars.USERNAME }}
        key: ${{ secrets.SECRET_KEY }}
