name: remote ssh command
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Update repository
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ${{ github.event.repository.name }}
          printf "\n\n updating repository...."
          git pull
          
          printf "\n\n generating docker image...."
          docker build -t ${{ github.event.repository.name }} .

        host: ${{ vars.HOST }}
        user: ${{ vars.USERNAME }}
        key: ${{ secrets.SECRET_KEY }}

  deploy-dev:
    name: deploy-dev
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          printf "\n\n starting docker server on port *** ...."
          docker run -d -p 8282:8080 --name containerdev --restart=always ${{ github.event.repository.name }}:latest

        host: ${{ vars.HOST }}
        user: ${{ vars.USERNAME }}
        key: ${{ secrets.SECRET_KEY }}