name: remote ssh command
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          sudo whoami
        host: ${{ vars.HOST }}
        user: ${{ vars.USERNAME }}
        pass: Pardamuca@1
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.SECRET_KEY }}
        port: ${{ vars.PORT }}
        script: whoami

