name: remote ssh command
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ $HOST }}
        username: ${{ $USERNAME }}
        key: ${{ secrets.SECRET_KEY }}
        port: ${{ $PORT }}
        script: whoami
    